[package]
name = "blockchain_web_api"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
axum = "0.8"
tower = { version = "0.5", features = ["full"] }

[[bin]]
name = "blockchain_web_api"
path = "src/main.rs"
